# Generated by Django 5.2 on 2025-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(),
        ),
    ]
