# Generated by Django 5.2 on 2025-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_end_time_plan_start_time_alter_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_privacy',
            field=models.CharField(choices=[('public', '公開'), ('private', '私人')], default='public', help_text='設定帳號隱私狀態，決定其他用戶是否可以查看您的個人資料', max_length=10),
        ),
    ]
