# Generated by Django 5.2 on 2025-07-03 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_end_time_plan_start_time_alter_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_privacy',
            field=models.CharField(choices=[('public', '公開'), ('private', '私人')], default='public', help_text='設定帳號隱私狀態，決定其他用戶是否可以查看您的個人資料', max_length=10),
        ),
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
