# Generated by Django 5.2 on 2025-06-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_account_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow_request_from',
            field=models.ForeignKey(blank=True, help_text='發送追蹤請求的使用者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_follow',
            field=models.ForeignKey(blank=True, help_text='相關的追蹤關係', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userfollow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert'), ('custom', 'Custom'), ('follow_request', 'Follow Request')], max_length=50),
        ),
    ]
