# Generated by Django 5.2 on 2025-07-03 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_account_privacy_follownotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='follow_request_from',
            field=models.ForeignKey(blank=True, help_text='發送追蹤請求的使用者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
