# Generated by Django 5.2 on 2025-07-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_follownotification_follow_request_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='related_follow',
            field=models.ForeignKey(blank=True, help_text='相關的追蹤關係', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userfollow'),
        ),
    ]
