# Generated by Django 5.2 on 2025-07-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follownotification_related_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follownotification',
            name='related_follow',
        ),
    ]
