# Generated by Django 5.2 on 2025-07-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petfeed',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_feeds', to='pets.pet', verbose_name='寵物'),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='feeds.feed', verbose_name='飼料'),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
        migrations.AlterUniqueTogether(
            name='petfeed',
            unique_together={('pet', 'feed')},
        ),
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together={('user', 'feed')},
        ),
    ]
