# Generated by Django 4.2.20 on 2025-07-15 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feeds", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfeed",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userfeed",
            name="feed",
        ),
        migrations.RemoveField(
            model_name="userfeed",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="feed",
            options={},
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="feed_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="extracted_text",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="popularity",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="processing_error",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="processing_status",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="feed",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="front_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="nutrition_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="user_id",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feed",
            name="calcium",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="carbohydrate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="fat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="magnesium",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="phosphorus",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="protein",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="feed",
            name="sodium",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="PetFeed",
        ),
        migrations.DeleteModel(
            name="UserFeed",
        ),
    ]
