# Generated by Django 4.2.20 on 2025-07-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_alter_userfeed_unique_together_remove_userfeed_feed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="user_id",
            new_name="user",
        ),
    ]
