# Generated by Django 4.2.20 on 2025-07-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_rename_user_id_feed_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="feed",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
