# Generated by Django 4.2.20 on 2025-07-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0005_rename_user_feed_user_id_alter_feed_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="user_id",
            new_name="user",
        ),
    ]
