# Generated by Django 5.2 on 2025-07-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_userfeed_alter_feed_unique_together_feed_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_calcium',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_carbohydrate',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_fat',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_magnesium',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_phosphorus',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_protein',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='custom_sodium',
        ),
    ]
