# Generated by Django 5.2 on 2025-07-29 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_remove_userfeed_custom_calcium_and_more'),
        ('pets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='marked',
            field=models.BooleanField(default=False, help_text='是否標記為精選飼料'),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='使用此飼料的寵物', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_feeds', to='pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together={('user', 'feed', 'pet')},
        ),
        migrations.AddIndex(
            model_name='userfeed',
            index=models.Index(fields=['pet', 'last_used_at'], name='feeds_userf_pet_id_1d211c_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeed',
            index=models.Index(fields=['marked'], name='feeds_userf_marked_bd99ac_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeed',
            index=models.Index(fields=['user', 'marked'], name='feeds_userf_user_id_80c176_idx'),
        ),
    ]
