# Generated by Django 5.2 on 2025-07-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_alter_userfeed_unique_together_userfeed_marked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='front_image_path',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='front_image_url',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='nutrition_image_path',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='nutrition_image_url',
        ),
    ]
