# Generated by Django 5.2 on 2025-07-31 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_remove_feed_front_image_path_and_more'),
        ('pets', '0009_delete_abnormalpostimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='飼料價格', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='UserFeedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='評分 1-5 顆星')),
                ('content', models.TextField(blank=True, help_text='評價內容', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='feeds.feed')),
                ('pet', models.ForeignKey(help_text='評價此飼料的寵物', on_delete=django.db.models.deletion.CASCADE, related_name='feed_ratings', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'rating'], name='feeds_userf_feed_id_aac166_idx'), models.Index(fields=['user', 'created_at'], name='feeds_userf_user_id_46673e_idx'), models.Index(fields=['pet', 'created_at'], name='feeds_userf_pet_id_a54732_idx')],
                'unique_together': {('user', 'feed', 'pet')},
            },
        ),
    ]
