# Generated by Django 5.2 on 2025-08-01 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_feed_is_verified_feed_review_count_alter_feed_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='userfeed',
            name='feeds_userf_marked_bd99ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='userfeed',
            name='feeds_userf_user_id_80c176_idx',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='marked',
        ),
        migrations.AddField(
            model_name='userfeedmark',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='userfeedmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfeedmark',
            index=models.Index(fields=['user', 'created_at'], name='feeds_userf_user_id_7daa67_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedmark',
            index=models.Index(fields=['feed', 'created_at'], name='feeds_userf_feed_id_e6944b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedmark',
            unique_together={('user', 'feed')},
        ),
    ]
