# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_userfeedmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederrorreport',
            name='corrected_data',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='使用者建議的正確資料',
            ),
        ),
        migrations.AddField(
            model_name='feederrorreport',
            name='original_data',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='原始錯誤資料',
            ),
        ),
        migrations.AlterField(
            model_name='feederrorreport',
            name='error_type',
            field=models.CharField(
                choices=[
                    ('name', '名稱錯誤'),
                    ('brand', '品牌錯誤'),
                    ('nutrition', '營養成分錯誤'),
                    ('price', '價格錯誤'),
                    ('image', '圖片錯誤'),
                    ('multiple', '多項錯誤'),
                    ('other', '其他錯誤')
                ],
                help_text='錯誤類型',
                max_length=20,
            ),
        ),
    ]