# Generated by Django 4.2.21 on 2025-06-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pet_avatar",
                    models.ImageField(blank=True, null=True, upload_to="pet_avatars/"),
                ),
                ("is_dog", models.BooleanField(default=False)),
                ("life_stage", models.CharField(max_length=20)),
                ("weight", models.FloatField()),
                ("expect_adult_weight", models.FloatField(blank=True, null=True)),
                ("litter_size", models.IntegerField(blank=True, null=True)),
                ("weeks_of_lactation", models.IntegerField(blank=True, null=True)),
                (
                    "keeper_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
