# Generated by Django 4.2.21 on 2025-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
