# Generated by Django 4.2.20 on 2025-07-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_feed_feed_image_alter_pet_pet_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feed",
        ),
    ]
