# Generated by Django 4.2.21 on 2025-06-30 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calculator", "0002_pet_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="keeper_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calculator_pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("calcium", models.FloatField(blank=True, null=True)),
                ("phosphorus", models.FloatField(blank=True, null=True)),
                ("magnesium", models.FloatField(blank=True, null=True)),
                ("sodium", models.FloatField(blank=True, null=True)),
                (
                    "keeper_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculator_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
