# Generated by Django 4.2.21 on 2025-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_alter_pet_keeper_id_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
