# Generated by Django 5.2 on 2025-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_delete_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='pet_name',
        ),
    ]
