# Generated by Django 4.2.21 on 2025-07-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_feed_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
