# Generated by Django 5.2 on 2025-07-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_name_pet_pet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_name',
            new_name='name',
        ),
    ]
