# Generated by Django 4.2.21 on 2025-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_feed_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="feed_image",
            field=models.URLField(
                blank=True,
                help_text="Firebase 上傳後的飼料圖片 URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="pet_avatar",
            field=models.URLField(
                blank=True,
                help_text="Firebase 上傳後的圖片 URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
