# Generated by Django 5.2 on 2025-07-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_rename_pet_name_pet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='pet_name',
        ),
    ]
