# Generated by Django 5.2 on 2025-07-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_rename_name_pet_pet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='expect_adult_weight',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='life_stage',
            new_name='pet_stage',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='length',
            new_name='predicted_adult_weight',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='litter_size',
        ),
    ]
