# Generated by Django 5.2 on 2025-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_expect_adult_weight_pet_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='keeper_id',
            new_name='owner',
        ),
    ]
