# Generated by Django 5.2 on 2025-07-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_rename_keeper_id_pet_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
