# Generated by Django 5.2 on 2025-05-06 08:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, help_text='年齡 (歲)', null=True)),
                ('breed', models.CharField(blank=True, help_text='品種', max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, help_text='體重 (公斤)', null=True)),
                ('height', models.FloatField(blank=True, help_text='身高 (公分)', null=True)),
                ('pet_stage', models.CharField(blank=True, choices=[('puppy', '幼犬'), ('adult', '成犬/成貓'), ('pregnant', '懷孕期'), ('lactating', '哺乳期'), ('kitten', '幼貓')], help_text='年齡階段', max_length=20, null=True)),
                ('predicted_adult_weight', models.FloatField(blank=True, help_text='預期成犬/成貓體重 (公斤)', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_title', models.CharField(max_length=100)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField()),
                ('popularity', models.IntegerField(default=0)),
                ('go_to_doctor', models.BooleanField(default=False)),
                ('health_status', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_archives', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_archives', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='AbnormalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('weight', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('water_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveIllnessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='pets.illness')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illnesses', to='pets.illnessarchive')),
            ],
            options={
                'unique_together': {('archive', 'illness')},
            },
        ),
        migrations.CreateModel(
            name='ArchiveAbnormalPostRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_links', to='pets.abnormalpost')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to='pets.illnessarchive')),
            ],
            options={
                'unique_together': {('archive', 'post')},
            },
        ),
        migrations.CreateModel(
            name='PetGenericRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_relations', to='pets.pet')),
            ],
            options={
                'unique_together': {('pet', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='PostSymptomsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='pets.abnormalpost')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pets.symptom')),
            ],
            options={
                'unique_together': {('post', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='ArchiveSymptomsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='pets.illnessarchive')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_archives', to='pets.symptom')),
            ],
            options={
                'unique_together': {('archive', 'symptom')},
            },
        ),
    ]
