# Generated by Django 5.2 on 2025-07-29 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIllnessRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('go_to_doctor', models.BooleanField(default=False)),
                ('health_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='年齡 (歲)', null=True)),
                ('breed', models.CharField(blank=True, help_text='品種', max_length=100, null=True)),
                ('height', models.FloatField(blank=True, help_text='身高 (公分)', null=True)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_stage', models.CharField(blank=True, choices=[('puppy', '幼犬'), ('adult', '成犬/成貓'), ('pregnant', '懷孕期'), ('lactating', '哺乳期'), ('kitten', '幼貓')], help_text='年齡階段', max_length=20, null=True)),
                ('pet_type', models.CharField(max_length=100)),
                ('predicted_adult_weight', models.FloatField(blank=True, help_text='預期成犬/成貓體重 (公斤)', null=True)),
                ('weight', models.FloatField(blank=True, help_text='體重 (公斤)', null=True)),
                ('weeks_of_lactation', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='寵物描述', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSymptomsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AbnormalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_amount', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAbnormalPostRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_links', to='pets.abnormalpost')),
            ],
        ),
    ]
