# Generated by Django 5.2 on 2025-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, help_text='寵物簡介', null=True),
        ),
    ]
