# Generated by Django 5.2 on 2025-07-29 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcontent',
            name='postFrame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_archives_postFrame', to='social.postframe'),
        ),
        migrations.AddField(
            model_name='archiveillnessrelation',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illnesses', to='pets.forumcontent'),
        ),
        migrations.AddField(
            model_name='archiveabnormalpostrelation',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to='pets.forumcontent'),
        ),
        migrations.AddField(
            model_name='archiveillnessrelation',
            name='illness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='pets.illness'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumcontent',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_archives', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='abnormalpost',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_posts', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='postsymptomsrelation',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='pets.abnormalpost'),
        ),
        migrations.AddField(
            model_name='postsymptomsrelation',
            name='symptom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pets.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='archiveabnormalpostrelation',
            unique_together={('archive', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='archiveillnessrelation',
            unique_together={('archive', 'illness')},
        ),
        migrations.AlterUniqueTogether(
            name='postsymptomsrelation',
            unique_together={('post', 'symptom')},
        ),
    ]
