# Generated by Django 5.2 on 2025-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.FloatField(blank=True, help_text='年齡 (歲)', null=True),
        ),
    ]
