# Generated by Django 5.2 on 2025-07-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_dog',
            field=models.BooleanField(default=False),
        ),
    ]
