# Generated by Django 5.2 on 2025-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_is_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weeks_of_lactation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
