# Generated by Django 5.2 on 2025-07-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_weeks_of_lactation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_dog',
        ),
    ]
