# Generated by Django 5.2 on 2025-07-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_pet_is_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalpost',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abnormalpost',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abnormalpost',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abnormalpost',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='abnormalpost',
            name='water_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abnormalpost',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
