# Generated by Django 5.2 on 2025-07-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_abnormalpost_is_emergency_abnormalpost_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(help_text='Firebase Storage 公開 URL', max_length=500)),
                ('firebase_path', models.CharField(help_text='Firebase Storage 檔案路徑', max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='圖片排序順序')),
                ('original_filename', models.CharField(blank=True, help_text='原始檔案名稱', max_length=255)),
                ('content_type_mime', models.CharField(default='image/jpeg', help_text='檔案 MIME 類型', max_length=100)),
                ('alt_text', models.CharField(blank=True, help_text='圖片替代文字', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='檔案大小（bytes）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('abnormal_post', models.ForeignKey(help_text='關聯的異常貼文', on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_images', to='pets.abnormalpost')),
            ],
            options={
                'verbose_name': '異常貼文圖片',
                'verbose_name_plural': '異常貼文圖片',
                'ordering': ['abnormal_post', 'sort_order'],
                'indexes': [models.Index(fields=['abnormal_post', 'sort_order'], name='pets_abnorm_abnorma_4501d6_idx')],
            },
        ),
    ]
