# Generated by Django 5.2 on 2025-07-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_abnormalpostimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbnormalPostImage',
        ),
    ]
