# Generated by Django 5.2 on 2025-08-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_delete_abnormalpostimage'),
        ('social', '0002_postframe_comments_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumContent',
            new_name='DiseaseArchiveContent',
        ),
    ]
