# Generated by Django 5.2 on 2025-08-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_add_is_private_to_abnormalpost'),
        ('pets', '0010_rename_forumcontent_diseasearchivecontent'),
    ]

    operations = [
    ]
