# Generated by Django 5.2 on 2025-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_merge_20250806_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasearchivecontent',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abnormalpost',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
