# Generated by Django 5.2.5 on 2025-09-02 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionresult',
            name='pet_photo',
        ),
        migrations.CreateModel(
            name='BulletinPetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(blank=True, help_text='Firebase Storage 圖片 URL', max_length=500, null=True)),
                ('firebase_path', models.CharField(blank=True, help_text='Firebase Storage 檔案路徑', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File Size', null=True)),
                ('content_type_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='替代文字', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_image', to='auctions.auctionresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
