# Generated by Django 4.2.21 on 2025-09-09 01:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0002_remove_auctionresult_pet_photo_bulletinpetimage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("session", "user")},
        ),
    ]
