from django.urls import path
from .views import *

urlpatterns = [
    path('create/', CreatePetAPIView.as_view(), name='create-pet'),
    path('<int:pet_id>/update/', UpdatePetAPIView.as_view(), name='update-pet'),
    path('<int:pet_id>/detail/', PetDetailAPIView.as_view(), name='pet-detail'),
    path('illness-archives/popular-today/', TodayPopularIllnessArchiveAPIView.as_view(), name='today-popular-illness-archives'),
    path('my-pets/', UserPetsAPIView.as_view(), name='user_pets'),
    path('users/<int:pk>/archives/', UserIllnessArchiveListAPIView.as_view(), name='user-archives'),
    path('abnormal-posts/create/', CreateAbnormalPostAPIView.as_view(), name='create-abnormal-post'),
    path('symptoms/', SymptomListAPIView.as_view(), name='symptom-list'),
    path('my-abnormal-posts/', UserAbnormalPostListAPIView.as_view(), name='user-abnormal-posts'),
    path('<int:pet_id>/abnormal-posts/', PetAbnormalPostsAPIView.as_view(), name='pet-abnormal-posts'),
    path('<int:pet_id>/abnormal-posts/preview/', PetAbnormalPostsPreviewAPIView.as_view(), name='pet-abnormal-posts-preview'),
    path('<int:pet_id>/abnormal-post/<int:post_id>/', AbnormalPostDetailAPIView.as_view(), name='abnormal-post-detail'),
    path('abnormal-post/<int:post_id>/public/', PublicAbnormalPostDetailAPIView.as_view(), name='public-abnormal-post-detail'),
    path('<int:pet_id>/abnormal-post/<int:post_id>/update/', UpdateAbnormalPostAPIView.as_view(), name='update-abnormal-post'),
    path('<int:pet_id>/abnormal-post/<int:post_id>/delete/', DeleteAbnormalPostAPIView.as_view(), name='delete-abnormal-post'),
    path('disease-archive/generate-content/', GenerateDiseaseArchiveContentAPIView.as_view(), name='generate-disease-archive-content'),
    path('disease-archive/create/', CreateDiseaseArchiveAPIView.as_view(), name='create-disease-archive'),
    path('my-disease-archives/preview/', GetMyDiseaseArchivesPreviewAPIView.as_view(), name='my-disease-archives-preview'),
    path('disease-archive/<int:archive_id>/', DiseaseArchiveDetailAPIView.as_view(), name='disease-archive-detail'),
    path('disease-archives/public/preview/', PublicDiseaseArchivesPreviewAPIView.as_view(), name='public-disease-archives-preview'),
    path('users/<int:user_id>/disease-archives/public/preview/', UserPublicDiseaseArchivesPreviewAPIView.as_view(), name='user-public-disease-archives-preview'),
    path('my-public-disease-archives/preview/', UserPublicDiseaseArchivesPreviewAPIView.as_view(), name='my-public-disease-archives-preview'),
    path('disease-archive/<int:archive_id>/publish/', PublishDiseaseArchiveAPIView.as_view(), name='publish-disease-archive'),
    path('disease-archive/<int:archive_id>/update/', UpdateDiseaseArchiveAPIView.as_view(), name='update-disease-archive'),
    path('disease-archive/<int:archive_id>/delete/', DeleteDiseaseArchiveAPIView.as_view(), name='delete-disease-archive'),
    path('disease-archive/<int:archive_id>/like/', DiseaseArchiveLikeAPIView.as_view(), name='disease-archive-like'),
    path('disease-archive/<int:archive_id>/save/', DiseaseArchiveSaveAPIView.as_view(), name='disease-archive-save'),
    path('disease-archives/recommended/', RecommendedDiseaseArchivesAPIView.as_view(), name='recommended-disease-archives'),
]