# Generated by Django 4.2.20 on 2025-07-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0007_abnormalpost_is_emergency_abnormalpost_record_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reports",
                        to="pets.pet",
                    ),
                ),
            ],
        ),
    ]
