# Generated by Django 4.2.21 on 2025-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthreport",
            name="check_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthreport",
            name="check_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthreport",
            name="check_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthreport",
            name="notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
