# Generated by Django 4.2.21 on 2025-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrapp", "0002_healthreport_check_date_healthreport_check_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthreport",
            name="check_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cbc", "全血計數"),
                    ("biochemistry", "血液生化檢查"),
                    ("urinalysis", "尿液分析"),
                    ("other", "其他"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
