# Generated by Django 5.2 on 2025-07-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_initial'),
        ('ocrapp', '0003_alter_healthreport_check_type_and_more'),
    ]

    operations = [
    ]
