# Generated by Django 5.2 on 2025-10-30 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(blank=True, help_text='Frontend conversation ID (from aiAgent app)', null=True)),
                ('thread_id', models.CharField(help_text='OpenAI thread ID', max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='New Conversation', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if user deleted/archived')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_agent_threads',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='ai_agent_th_user_id_7c95bd_idx'), models.Index(fields=['thread_id'], name='ai_agent_th_thread__c6b2cf_idx'), models.Index(fields=['conversation_id'], name='ai_agent_th_convers_815fd5_idx')],
            },
        ),
    ]
