# Generated by Django 5.2 on 2025-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentthread',
            name='ai_agent_th_convers_815fd5_idx',
        ),
        migrations.RemoveField(
            model_name='agentthread',
            name='conversation_id',
        ),
        migrations.AlterField(
            model_name='agentthread',
            name='thread_id',
            field=models.CharField(help_text="OpenAI conversation ID (starts with 'conv-')", max_length=255, unique=True),
        ),
    ]
