# Generated by Django 5.2.5 on 2025-10-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_agentmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'AI Agent Message', 'verbose_name_plural': 'AI Agent Messages'},
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores: recommendedUsers {}, recommendedSocialPosts {}, recommendedForumPosts {}, operations [], operationParams {}', verbose_name='Additional data'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confidence score'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='Pet breeds, symptoms, time ranges, etc.', verbose_name='Extracted entities'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='has_calculator',
            field=models.BooleanField(default=False, help_text='Shows calculator button', verbose_name='Has calculator'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='has_operation',
            field=models.BooleanField(default=False, help_text='Shows operation button', verbose_name='Has operation'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='has_tutorial',
            field=models.BooleanField(default=False, help_text='Shows tutorial button', verbose_name='Has tutorial'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='intent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Detected intent'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='operation_type',
            field=models.CharField(blank=True, help_text='navigate, fill_form, click, etc.', max_length=50, null=True, verbose_name='Operation type'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='source',
            field=models.CharField(default='mcp_agent', max_length=50, verbose_name='Response source'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='tutorial_type',
            field=models.CharField(blank=True, help_text='health, training, nutrition, etc.', max_length=50, null=True, verbose_name='Tutorial type'),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='content',
            field=models.TextField(verbose_name='Message content'),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.agentthread', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['role'], name='ai_agent_me_role_325ffc_idx'),
        ),
    ]
