# Generated by Django 5.2.5 on 2025-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_agentmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmessage',
            name='has_operation',
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='operation_type',
            field=models.CharField(blank=True, help_text='navigate, fill_form, click, etc. (hasOperation derived from operations array in additional_data)', max_length=50, null=True, verbose_name='Operation type'),
        ),
    ]
