# Generated by Django 5.2.5 on 2025-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_remove_agentmessage_has_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmessage',
            name='has_calculator',
            field=models.BooleanField(default=False, help_text='DEPRECATED - No longer used', verbose_name='Has calculator (DEPRECATED)'),
        ),
    ]
