# Generated by Django 5.2 on 2025-08-24 08:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='站點名稱')),
                ('description', models.TextField(blank=True, verbose_name='站點描述')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='站點的緯度座標', max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='站點的經度座標', max_digits=11, verbose_name='經度')),
                ('radius', models.IntegerField(default=50, help_text='簽到有效範圍（公尺）', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='簽到範圍')),
                ('base_bid_price', models.IntegerField(default=100, help_text='站點競標的基礎價格（金幣）', validators=[django.core.validators.MinValueValidator(1)], verbose_name='起標價')),
                ('total_checkins', models.IntegerField(default=0, verbose_name='總簽到次數')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='熱門度分數')),
                ('status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用'), ('maintenance', '維護中')], default='active', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '站點',
                'verbose_name_plural': '站點',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='interactive_latitud_28b5c7_idx'), models.Index(fields=['status'], name='interactive_status_d0ac12_idx'), models.Index(fields=['-popularity_score'], name='interactive_popular_5baeef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='競標標題')),
                ('description', models.TextField(blank=True, verbose_name='競標描述')),
                ('min_bid', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最低出價')),
                ('current_bid', models.IntegerField(default=0, verbose_name='當前最高出價')),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('display_duration_days', models.IntegerField(default=7, verbose_name='展示期限（天）')),
                ('status', models.CharField(choices=[('pending', '待開始'), ('active', '進行中'), ('ended', '已結束'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('current_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bids', to=settings.AUTH_USER_MODEL, verbose_name='當前最高出價者')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL, verbose_name='得標者')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='interactivecity.checkpoint', verbose_name='站點')),
            ],
            options={
                'verbose_name': '競標',
                'verbose_name_plural': '競標',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('earn', '獲得'), ('spend', '消費'), ('refund', '退款'), ('bonus', '獎勵')], max_length=20, verbose_name='交易類型')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額')),
                ('balance_before', models.IntegerField(verbose_name='交易前餘額')),
                ('balance_after', models.IntegerField(verbose_name='交易後餘額')),
                ('reason', models.CharField(max_length=200, verbose_name='交易原因')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='關聯類型')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='關聯ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '金幣交易',
                'verbose_name_plural': '金幣交易',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('acquired_through', models.CharField(choices=[('auction', '競標獲得'), ('special', '特殊活動'), ('admin', '管理員授予')], max_length=20, verbose_name='獲得方式')),
                ('status', models.CharField(choices=[('active', '使用中'), ('expired', '已過期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_rights', to='interactivecity.auction', verbose_name='相關競標')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_rights', to='interactivecity.checkpoint', verbose_name='站點')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_rights', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '展示權',
                'verbose_name_plural': '展示權',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='任務標題')),
                ('description', models.TextField(verbose_name='任務描述')),
                ('type', models.CharField(choices=[('daily', '每日任務'), ('route', '路線挑戰'), ('special', '特殊任務')], max_length=20, verbose_name='任務類型')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='easy', max_length=20, verbose_name='難度')),
                ('required_checkins', models.IntegerField(verbose_name='需要簽到的站點數量')),
                ('reward_coins', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='金幣獎勵')),
                ('bonus_reward', models.IntegerField(default=0, verbose_name='額外獎勵')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已完成'), ('expired', '已過期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='狀態')),
                ('progress', models.IntegerField(default=0, verbose_name='完成進度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactivecity_missions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '任務',
                'verbose_name_plural': '任務',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='使用者緯度')),
                ('user_longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='使用者經度')),
                ('location_accuracy', models.FloatField(verbose_name='定位精確度（公尺）')),
                ('distance_to_checkpoint', models.FloatField(verbose_name='到站點的距離（公尺）')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='簽到時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用戶代理')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('validation_notes', models.TextField(blank=True, verbose_name='驗證備註')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='interactivecity.checkpoint', verbose_name='站點')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='interactivecity.mission', verbose_name='相關任務')),
            ],
            options={
                'verbose_name': '簽到記錄',
                'verbose_name_plural': '簽到記錄',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MissionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactivecity.checkpoint', verbose_name='站點')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactivecity.mission', verbose_name='任務')),
            ],
            options={
                'verbose_name': '任務站點',
                'verbose_name_plural': '任務站點',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='target_checkpoints',
            field=models.ManyToManyField(related_name='missions', through='interactivecity.MissionCheckpoint', to='interactivecity.checkpoint', verbose_name='目標站點'),
        ),
        migrations.CreateModel(
            name='UserCoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='餘額')),
                ('total_earned', models.IntegerField(default=0, verbose_name='累計獲得')),
                ('total_spent', models.IntegerField(default=0, verbose_name='累計消費')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_balance', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者金幣餘額',
                'verbose_name_plural': '使用者金幣餘額',
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='出價金額')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='出價時間')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='interactivecity.auction', verbose_name='競標')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL, verbose_name='出價者')),
            ],
            options={
                'verbose_name': '競標出價記錄',
                'verbose_name_plural': '競標出價記錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['auction', '-timestamp'], name='interactive_auction_10fe22_idx'), models.Index(fields=['bidder', '-timestamp'], name='interactive_bidder__b8bedb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['checkpoint', 'status'], name='interactive_checkpo_e8db60_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['end_date'], name='interactive_end_dat_785fde_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['winner'], name='interactive_winner__26954b_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['user', '-created_at'], name='interactive_user_id_527a42_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['type'], name='interactive_type_1b6b24_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='interactive_referen_c57994_idx'),
        ),
        migrations.AddIndex(
            model_name='displayright',
            index=models.Index(fields=['checkpoint', 'status'], name='interactive_checkpo_b9513e_idx'),
        ),
        migrations.AddIndex(
            model_name='displayright',
            index=models.Index(fields=['user', 'status'], name='interactive_user_id_ff197a_idx'),
        ),
        migrations.AddIndex(
            model_name='displayright',
            index=models.Index(fields=['start_date', 'end_date'], name='interactive_start_d_13ddca_idx'),
        ),
        migrations.AddConstraint(
            model_name='displayright',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('checkpoint',), name='unique_active_display_right_per_checkpoint'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-timestamp'], name='interactive_user_id_354eda_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['checkpoint', '-timestamp'], name='interactive_checkpo_08b4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['mission'], name='interactive_mission_deabce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missioncheckpoint',
            unique_together={('mission', 'checkpoint')},
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['user', 'status'], name='interactive_user_id_461257_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['type', 'status'], name='interactive_type_8d6f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['expires_at'], name='interactive_expires_99949b_idx'),
        ),
    ]
