# Generated by Django 5.2 on 2025-07-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHeadshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(blank=True, help_text='Firebase Storage 圖片 URL', max_length=500, null=True)),
                ('firebase_path', models.CharField(blank=True, help_text='Firebase Storage 檔案路徑', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File Size', null=True)),
                ('content_type_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='替代文字', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHeadshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(blank=True, help_text='Firebase Storage 圖片 URL', max_length=500, null=True)),
                ('firebase_path', models.CharField(blank=True, help_text='Firebase Storage 檔案路徑', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File Size', null=True)),
                ('content_type_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='替代文字', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(blank=True, help_text='Firebase Storage 圖片 URL', max_length=500, null=True)),
                ('firebase_path', models.CharField(blank=True, help_text='Firebase Storage 檔案路徑', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File Size', null=True)),
                ('content_type_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='替代文字', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['id', 'sort_order'],
            },
        ),
    ]
