# Generated by Django 5.2 on 2025-07-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('pets', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='postFrame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.postframe'),
        ),
        migrations.AddField(
            model_name='petheadshot',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headshot', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='userheadshot',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headshot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['id'], name='media_image_id_798f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['firebase_path'], name='media_image_firebas_532ec0_idx'),
        ),
    ]
