# Generated by Django 5.2 on 2025-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petheadshot',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userheadshot',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='petheadshot',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userheadshot',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['public_id'], name='media_image_public__60fdc6_idx'),
        ),
    ]
