# Generated by Django 5.2 on 2025-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_image_content_type_mime_image_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='petheadshot',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userheadshot',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
