"""
Django settings for gradProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os  


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9$@4-v*$7-=1r-l@3(fytpr_*f1b!@z^j00f%31hcp6(udqh6s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to True for development

# Allow common hosts; when DEBUG is True, allow all to simplify mobile/emulator testing
ALLOWED_HOSTS = [
    'peter.geniusbee.net',
    'localhost',
    '127.0.0.1',
    '10.0.2.2',  # Android emulator to host loopback
    'geniusbee.net',
    '.geniusbee.net',  # Allows all subdomains
    '140.119.19.25',
]
if DEBUG:
    # For local development, accept any Host header to support LAN IPs and emulator access
    ALLOWED_HOSTS = ['*']

# Development settings - disable SSL/HTTPS redirects
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Proxy settings for reverse proxy setup
USE_X_FORWARDED_HOST = True  # Enable for reverse proxy
USE_X_FORWARDED_PORT = True  # Enable for reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Enable for HTTPS behind proxy


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "pets",
    "social",
    "feeds",
    "interactions",
    "comments",
    "media",
    "articleRecommendation",
    "calculator",
    "ocrapp",
    "auctions",
    "interactivecity",
    "aiAgent",
    "ai",  # ChatKit and AI services
    'sslserver',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Handle CORS as early as possible
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files when Django runs behind Passenger/gunicorn.
    # Added conditionally below so local development without it keeps working.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS configuration for production
CORS_ALLOW_ALL_ORIGINS = False  # Set to False for production security

# For production, specify allowed origins:
CORS_ALLOWED_ORIGINS = [
    "https://peter.geniusbee.net",
    "https://geniusbee.net",
    "https://peter.geniusbee.net:4173",  # Vite preview server with domain
    "https://peter.geniusbee.net:5173",  # Vite dev server with domain
    "https://hodgepodge-studio.com",       # frontend hosted on the VPS
    "https://www.hodgepodge-studio.com",
    "https://peter.hodgepodge-studio.com",
    "https://localhost",  # WebView/live-reload over HTTPS default port
    "http://localhost:3000",  # Local development
    "http://localhost:5173",  # Vite default port
    "https://localhost:5173",  # Vite default port (HTTPS)
    "http://localhost:4173",  # Vite preview server
    "https://localhost:4173",  # Vite preview server (HTTPS)
    "http://localhost:8000",  # Django development server
    "https://localhost:443",
    "http://127.0.0.1:5173",  # Vite on 127.0.0.1
    "https://127.0.0.1:5173",  # Vite on 127.0.0.1 (HTTPS)
    "http://127.0.0.1:4173",  # Vite preview server
    "https://127.0.0.1:4173",  # Vite preview server (HTTPS)
]

# Support non-HTTP mobile WebView schemes and local/emulator IPs
# django-cors-headers only allows http/https in CORS_ALLOWED_ORIGINS, so use regexes for capacitor/ionic
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^capacitor://localhost$",
    r"^ionic://localhost$",
    r"^https://localhost$",
    r"^http://10\.0\.2\.2(:\d+)?$",  # Android emulator
    r"^http://192\.168\.[0-9]{1,3}\.[0-9]{1,3}(:\d+)?$",  # Local LAN
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Handle preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF trusted origins (mainly relevant when using SessionAuthentication or HTTPS forms)
CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "http://localhost:5173",
    "https://localhost:5173",
    "http://localhost:4173",
    "https://localhost:4173",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "https://127.0.0.1:5173",
    "http://10.0.2.2:8000",
    "https://peter.geniusbee.net",
    "https://geniusbee.net",
    "https://hodgepodge-studio.com",
    "https://*.hodgepodge-studio.com",  # Cloudflare Tunnel
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework 設置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'utils.exception_handler.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
}

# JWT 設置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    # 添加寬鬆時間以處理時鐘同步問題
    'LEEWAY': timedelta(seconds=10),
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
}

ROOT_URLCONF = 'gradProject.urls'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# File upload settings - Set max upload size to 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gradProject.wsgi.application'
ASGI_APPLICATION = 'gradProject.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'accounts.CustomUser'

# Public sign-up. Set REGISTRATION_OPEN=False on deployments where only you should
# be able to create accounts (e.g. the demo server, to keep AI usage under control).
# With an invite code set, /api/v1/accounts/register/ still accepts requests that
# include the matching "invite_code" field.
REGISTRATION_OPEN = os.environ.get('REGISTRATION_OPEN', 'True').lower() not in ('false', '0', 'no')
REGISTRATION_INVITE_CODE = os.environ.get('REGISTRATION_INVITE_CODE', '')
RECOMMENDATIONS_ENABLED = False


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # target of `manage.py collectstatic`

# Serve those collected files ourselves when WhiteNoise is available (VPS deployment).
try:
    import whitenoise  # noqa: F401
except ImportError:
    pass
else:
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(
            MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
            'whitenoise.middleware.WhiteNoiseMiddleware',
        )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Firebase Storage 配置
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'config', 'petapp-c2e46-firebase-adminsdk-fbsvc-0ec3a87ef4.json')
FIREBASE_STORAGE_BUCKET = 'petapp-c2e46.firebasestorage.app'

# Where uploaded images go: 'firebase' (bucket above) or 'local' (this machine).
IMAGE_STORAGE_BACKEND = os.environ.get('IMAGE_STORAGE_BACKEND', 'firebase')
# Local image storage (IMAGE_STORAGE_BACKEND=local), served by Django at LOCAL_IMAGE_URL
LOCAL_IMAGE_ROOT = os.environ.get('LOCAL_IMAGE_ROOT', os.path.join(BASE_DIR, 'uploaded_images'))
LOCAL_IMAGE_URL = '/media/images/'
# When the frontend is served from a different address than this backend (e.g. the
# frontend on the VPS calling this API), image links must be absolute. Set this to
# the backend's public address, e.g. https://peter.hodgepodge-studio.com
PUBLIC_MEDIA_BASE_URL = os.environ.get('PUBLIC_MEDIA_BASE_URL', '').rstrip('/')

# 日誌配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'auth_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'auth.log'),
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts.serializers': {
            'handlers': ['console', 'auth_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# 確保日誌目錄存在
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# HTTPS and Security Settings
# Avoid redirecting HTTP->HTTPS in local development to prevent CORS preflight redirects.
if DEBUG:
    SECURE_SSL_REDIRECT = False
    # Trust X-Forwarded-Proto from the HTTPS proxy (Cloudflare Tunnel / nginx) so
    # links Django builds use https:// when accessed through the domain.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# ============================================================================
# OpenAI Configuration
# ============================================================================

# OpenAI API Key for ChatKit and AI services
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# OpenAI Workflow ID for ChatKit sessions
# Create a workflow at https://platform.openai.com
# ChatKit uses workflows instead of assistants
OPENAI_WORKFLOW_ID = os.environ.get('OPENAI_WORKFLOW_ID', '')

# MCP Server Configuration
# The MCP server runs on port 5000 by default (see backend/mcp_server/start.py)
MCP_SERVER_URL = os.environ.get('MCP_SERVER_URL', 'https://peter.geniusbee.net/mcp')

# How Django reaches the MCP tools:
#   'sse'       - separate MCP server process at MCP_SERVER_URL (local development)
#   'inprocess' - same process, no port, nothing exposed (shared hosting: one app only)
MCP_TRANSPORT = os.environ.get('MCP_TRANSPORT', 'sse')

# PETer AI agent model (ai/PETer_Agent.py)
# Model ID from https://developers.openai.com/api/docs/models/gpt-5.6-terra
PETER_AGENT_MODEL = os.environ.get('PETER_AGENT_MODEL', 'gpt-5.6-terra')
# Reasoning effort: 'low' suits a latency-sensitive tool-calling chat agent.
# The installed openai SDK accepts: minimal, low, medium, high.
PETER_AGENT_REASONING_EFFORT = os.environ.get('PETER_AGENT_REASONING_EFFORT', 'low')

# Voice chat (Realtime API) model, used by ai/views.py create_realtime_session.
# gpt-4o-realtime-preview models are no longer available; gpt-realtime-2.1 is the
# current realtime model with tool calling (https://developers.openai.com/api/docs/models/gpt-realtime-2.1)
REALTIME_MODEL = os.environ.get('REALTIME_MODEL', 'gpt-realtime-2.1')

# Voice chat: how easily background noise counts as the user speaking.
# Turn detection: 'server_vad' (volume based, uses THRESHOLD) or 'semantic_vad' (meaning based, uses EAGERNESS)
REALTIME_TURN_DETECTION = os.environ.get('REALTIME_TURN_DETECTION', 'server_vad')
# server_vad: 0.0-1.0, higher = needs louder speech, ignores more background noise (was 0.5)
REALTIME_VAD_THRESHOLD = float(os.environ.get('REALTIME_VAD_THRESHOLD', '0.7'))
# server_vad: silence (ms) before the user's turn is considered finished
REALTIME_VAD_SILENCE_MS = int(os.environ.get('REALTIME_VAD_SILENCE_MS', '1000'))
# semantic_vad: 'low' waits longest before replying / interrupting; 'medium', 'high', 'auto'
REALTIME_SEMANTIC_EAGERNESS = os.environ.get('REALTIME_SEMANTIC_EAGERNESS', 'low')
# Input noise reduction: 'far_field' (laptop/phone mic), 'near_field' (headset), or 'off'
REALTIME_NOISE_REDUCTION = os.environ.get('REALTIME_NOISE_REDUCTION', 'far_field')

# Optional: ChatKit API base URL (defaults to https://api.openai.com)
CHATKIT_API_BASE = os.environ.get('CHATKIT_API_BASE', 'https://api.openai.com')

# Optional: OpenAI model configuration
OPENAI_DEFAULT_MODEL = os.environ.get('OPENAI_DEFAULT_MODEL', 'gpt-4o')
OPENAI_MAX_TOKENS = int(os.environ.get('OPENAI_MAX_TOKENS', '4000'))


