# Generated by Django 5.2 on 2025-07-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downvotes', models.IntegerField(default=0, help_text='點踩數')),
                ('saves', models.IntegerField(default=0, help_text='收藏數')),
                ('shares', models.IntegerField(default=0, help_text='分享數')),
                ('upvotes', models.IntegerField(default=0, help_text='點讚數')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postframes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('postFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='social.postframe')),
            ],
        ),
        migrations.CreateModel(
            name='PostPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='pets.pet')),
                ('postFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_pets', to='social.postframe')),
            ],
        ),
        migrations.CreateModel(
            name='SoLContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='存儲具體內容文本')),
                ('postFrame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='social.postframe')),
            ],
        ),
    ]
