# Generated by Django 5.2 on 2025-07-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postframe',
            name='comments_count',
            field=models.IntegerField(default=0, help_text='評論數'),
        ),
    ]
