# Generated by Django 5.2 on 2025-07-16 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_url', models.URLField(help_text='關聯的圖片 Firebase URL', max_length=500)),
                ('x_position', models.FloatField(help_text='標註點在圖片上的 X 座標（百分比 0-100）')),
                ('y_position', models.FloatField(help_text='標註點在圖片上的 Y 座標（百分比 0-100）')),
                ('display_name', models.CharField(help_text='標註顯示的名稱', max_length=100)),
                ('target_type', models.CharField(choices=[('user', '用戶'), ('pet', '寵物')], help_text='標註目標類型', max_length=10)),
                ('target_id', models.PositiveIntegerField(help_text='標註目標的 ID（用戶 ID 或寵物 ID）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='創建此標註的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['firebase_url'], name='social_imag_firebas_a7b42f_idx'), models.Index(fields=['target_type', 'target_id'], name='social_imag_target__36b40a_idx')],
            },
        ),
    ]
