# Generated by Django 5.2 on 2025-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.URLField(blank=True, help_text='貼文圖片的URL，若有圖片則必填', null=True),
        ),
    ]
