# Generated by Django 5.2 on 2025-06-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageURL',
        ),
    ]
