# Generated by Django 5.2 on 2025-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_imageannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solcontent',
            name='location',
            field=models.CharField(blank=True, help_text='貼文地點位置', max_length=255, null=True),
        ),
    ]
