# Generated by Django 5.2 on 2025-07-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_solcontent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageannotation',
            name='display_name',
        ),
    ]
