# Generated by Django 5.2 on 2025-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_imageannotation_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postframe',
            name='likes',
            field=models.IntegerField(default=0, help_text='按讚數'),
        ),
    ]
