# Generated by Django 5.2 on 2025-07-19 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
        ('social', '0005_postframe_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'postFrame', 'relation')},
        ),
    ]
